on: 
  push: 
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run versioning scripts
        run: |
          pip install semversioner==1.7.0
          chmod +x ./ci-scripts/*.sh
          ./ci-scripts/bump-version.sh
          ./ci-scripts/git-commit.sh
          ./ci-scripts/git-tag.sh